version: "3.8"
services:  
  docker-node1:
    build: ./
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
      - 9229:9229
    volumes:
      - ./:/docker-node1
      - /node_modules
    command: sh -c "tmux new -d -s my_session;
      tmux send-keys -t my_session npm Space start C-m;
      tmux attach -t my_session"

